version: "3"

services:
  templates_next_app:
    image: registry.go.drimaesvn.com/fitivation/fitivation-web:staging
    restart: always
    environment:
      - VIRTUAL_HOST=fitivation-web.go.drimaesvn.com
      - LETSENCRYPT_HOST=fitivation-web.go.drimaesvn.com

networks:
  default:
    name: staging-net
    external: true
